apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-worker-deployment
  labels:
    app: pdf-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-worker
  template:
    metadata:
      labels:
        app: pdf-worker
    spec:
      containers:
      - name: pdf-worker
        image: ghcr.io/YOUR_USERNAME/YOUR_REPO:YOUR_TAG # <-- IMPORTANT: Replace with your actual image URL
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
